[FEATURE] CAF-10 User Management Interface Creation
gcachuo/ControlApp.Frontend pull request #3
Opened 2024-09-21 01:17 UTC by IvanJGG

2024-09-21 06:12 UTC, gcachuo requested changes

2024-09-21 06:12 UTC, gcachuo commented on views/users/add.php
> +                        <input type="text" class="form-control" id="Email" name="Email" placeholder="Introduce tu correo electrónico" required>
los id tienen que ser mas especificos, intenta con algo como `id="txtEmail"`

2024-09-21 06:12 UTC, gcachuo commented on views/users/add.php
> +                        <select class="form-control" id="Address" name="Address" required>
Cambialo a un input por el momento para poder terminar la tarea

2024-09-21 06:12 UTC, gcachuo commented on views/users/add.php
> +    await fetch('/actions/users/add.php', {
Para aprobarte el PR quita este fetch y reemplazalo por un mensaje

2024-09-21 06:12 UTC, gcachuo commented on views/users/add.php
> +                        <input type="text" class="form-control" id="Email" name="Email" placeholder="Introduce tu correo electrónico" required>
no debe ser `type="text"` cambialo a `type="email"`

2024-09-21 06:12 UTC, gcachuo commented on views/users/add.php
> +                        <input type="text" class="form-control" id="Password" name="Password" placeholder="Introduce la contraseña" required>
debe ser `type="password"` y `id="txtPassword"`

2024-09-21 06:12 UTC, gcachuo commented on views/users/add.php
> +                        <input type="text" class="form-control" id="Phone" name="Phone" placeholder="Introduce un teléfono" required>
`type="tel"`

2024-09-21 23:42 UTC, IvanJGG commented on views/users/add.php
> +    await fetch('/actions/users/add.php', {
literal, quito el fetch y solo pongo un alert?

2024-09-22 01:52 UTC, gcachuo requested changes

2024-09-22 01:52 UTC, gcachuo commented on views/users/add.php
> +                            <input type="text" class="form-control" id="FirstName" name="name" placeholder="Introduce tu primer nombre" required>
`name="name"` solo debe usarse una vez, cambialo a firstName

2024-09-22 01:52 UTC, gcachuo commented on views/users/add.php
> +                            <input type="text" class="form-control" id="SecondName" name="name" placeholder="Introduce tu segundo nombre">
`name="name"` solo debe usarse una vez, cambialo a secondName

2024-09-22 01:52 UTC, gcachuo commented on views/users/add.php
> +                        <input type="tel" class="form-control" id="Phone" name="Phone" placeholder="Introduce un teléfono" required>
`id="txtPhone" name="phone"`

2024-09-22 01:52 UTC, gcachuo commented on views/users/add.php
> +                        <input type="text" class="form-control" id="Address" name="Address" placeholder="Ingresa tu dirección" required>
`id="txtAddress" name="address"`

2024-09-22 04:59 UTC, gcachuo requested changes

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                        <label for="Email" class="form-label">Correo electrónico </label>
`for="txtEmail"`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                        <input type="email" class="form-control" id="txtEmail" name="Email" placeholder="Introduce tu correo electrónico" required>
`name="email"` con minuscula

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                            <input type="text" class="form-control" id="FirstName" name="name" placeholder="Introduce tu primer nombre" required>
`id="txtFirstName" name="firstName"`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                            <input type="text" class="form-control" id="SecondName" name="name" placeholder="Introduce tu segundo nombre">
`id="txtSecondName" name="secondName"`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                            <label for="SecondName" class="form-label">Segundo Nombre</label>
`for="txtSecondName"`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                            <input type="text" class="form-control" id="FirstSurname" name="name" placeholder="Introduce tu primer apellido">
`id="txtFirstName" name="firstName"`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                            <label for="FirstSurname" class="form-label">Primer Apellido </label>
`for="txtFirstName"`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                            <input type="text" class="form-control" id="SecondSurname" name="name" placeholder="Introduce tu segundo apellido">
`id="txtSecondName" name="secondSurname"`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                            <label for="SecondSurname" class="form-label">Segundo Apellido </label>
`for="txtSurname"`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                        <label for="Password" class="form-label">Contraseña </label>
`for="txtPassword"`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                        <input type="password" class="form-control" id="txtPassword" name="Password" placeholder="Introduce la contraseña" required>
`name="password"` en minusculas`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                        <label for="Phone" class="form-label">Teléfono </label>
`for="txtPhone"`

2024-09-22 04:59 UTC, gcachuo commented on views/users/add.php
> +                        <label for="Address" class="form-label">Dirección</label>
`for="txtAddress"`

2024-09-22 20:58 UTC, gcachuo approved these changes

2024-09-22 20:59 UTC, merged